export const Category = {
  LEISURE: "LEISURE",
  NECESSARY: "NECESSARY",
  SPORT: "SPORT",
  STUDY: "STUDY",
  DIFFERENT: "DIFFERENT",
  HYGIENE: "HYGIENE",
  CLEAN: "CLEAN",
  FAMILY: "FAMILY",
  PEOPLE: "PEOPLE",
} as const;
