export const Category = {
  LEISURE: "LEISURE",
  NECESSARY: "NECESSARY",
  SPORT: "SPORT",
  STUDY: "STUDY",
  DIFFERENT: "DIFFERENT",
  HYGIENE: "HYGIENE",
  CLEAN: "CLEAN",
  FAMILY: "FAMILY",
  PEOPLE: "PEOPLE",
  BOARDGAMES: "BOARDGAMES",
  BACK: "BACK",
  LANGUAGE: "LANGUAGE",
  CHILD: "CHILD",
  BONUS: "BONUS",
  PSORIASIS: "PSORIASIS",
  ROOMS: "ROOMS",
} as const;


